# Create new Users
POST http://localhost:5000/users/signup HTTP/1.1
content-type: application/json

{
    "name": "Muhammd Shahid",
    "email": "shahiking@gmail.com",
    "password": "shaidking"
}

###
# Login if user Available 
POST http://localhost:5000/users/login HTTP/1.1
content-type: application/json

{
    "email": "shahiking@gmail.com",
    "password": "shaidking"
}

###
# Get All the Logedin users
GET http://localhost:5000/users/barcodeusers HTTP/1.1
# content-type: application/json